config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :businesses do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  has_many :comments
  validates :name, presence: true, length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :business
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def index
    @business = Business.all
  end

  def show
    @business = Business.find(params[:id])
  end

  def new
    @business = Business.new
  end

  def edit
    @business = Business.find(params[:id])
  end

  def create
    @business = Business.new(business_params)

    if @business.save
      redirect_to @business
    else
      render 'new'
    end
  end

  def update
    @business = Business.find(params[:id])

    if @business.update(business_params)
      redirect_to @business
    else
      render 'edit'
    end
  end

  def destroy
    @business = Business.find(params[:id])
    @business.destroy
    redirect_to businesses_path
  end


  private

  def business_params
    params.require(:business).permit(:name, :description)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @business = Business.find(params[:business_id])
    @comment = @business.comments.create(comment_params)
    redirect_to business_path(@business)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/businesses/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @business) do |form| %>

<% if @business.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@business.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing Businesses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>description</th>
  </tr>

 <% @business.each do |x| %>
  <tr>
    <td><%= x.name %></td>
    <td><%= x.description %></td>
    <td><%= link_to 'Show', business_path(x) %></td>
    <td><%= link_to 'Edit', edit_business_path(x) %></td>
    <td><%= link_to 'Destroy', business_path(x),
             method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
 <% end %>
</table>

app/views/businesses/new.html.erb
<%= form_with scope: :business, url: businesses_path, local: true do |form| %>

  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@business.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @business.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @business.description %>
</p>

<h2>Comments</h2>
<% @business.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with(model: [ @business, @business.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_business_path(@business) %>
<%= link_to 'Back', businesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Yelp Project by Benjamin Sunderland</h1>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Hello User!</h1>

<%= link_to 'My Businesses', controller: 'businesses' %>
<%= link_to 'New Article', new_business_path %>